// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk5Kn5CdfbW28MqagekDCrIg7ky8ws3aI',
    appId: '1:251618113476:web:cb1b9b61f0f05c2de09691',
    messagingSenderId: '251618113476',
    projectId: 'tutorial-64f6e',
    authDomain: 'tutorial-64f6e.firebaseapp.com',
    storageBucket: 'tutorial-64f6e.firebasestorage.app',
    measurementId: 'G-XZWN8DXQD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzBr-yn-1fDXMhJLnwyKCO4ZNXCFhcFC8',
    appId: '1:251618113476:android:ebfef1de2256eb90e09691',
    messagingSenderId: '251618113476',
    projectId: 'tutorial-64f6e',
    storageBucket: 'tutorial-64f6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUh-IGcpSWe-8ULRCZ7s9kkar72NPIDls',
    appId: '1:251618113476:ios:040e81cc54914231e09691',
    messagingSenderId: '251618113476',
    projectId: 'tutorial-64f6e',
    storageBucket: 'tutorial-64f6e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUh-IGcpSWe-8ULRCZ7s9kkar72NPIDls',
    appId: '1:251618113476:ios:040e81cc54914231e09691',
    messagingSenderId: '251618113476',
    projectId: 'tutorial-64f6e',
    storageBucket: 'tutorial-64f6e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk5Kn5CdfbW28MqagekDCrIg7ky8ws3aI',
    appId: '1:251618113476:web:e760bf1528212061e09691',
    messagingSenderId: '251618113476',
    projectId: 'tutorial-64f6e',
    authDomain: 'tutorial-64f6e.firebaseapp.com',
    storageBucket: 'tutorial-64f6e.firebasestorage.app',
    measurementId: 'G-81ZM9E53YB',
  );
}
